config/routes.rb
InfluenceMarket::Application.routes.draw do

  match "users/top"=>'users#index',as: :users
  match 'users/:screen_name/followers' => 'users#followers' ,as: :followers
  match 'users/refresh' => 'users#refresh',as: :refresh_users

  resources :search do 
    collection do
      post :search_result
    end
  end

  resources :trades do
    member do 
      get :get_current_price
    end
  end

  resources :researchs
  resources :performances
  resources :sessions, :only => [:new, :create, :destroy]
  resources :home, :only => [:index]

   root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name,:followers_count, :screen_name, :twitter_id
  validates :screen_name,:twitter_id, uniqueness: true ,allow_blank: true,allow_nil: true


  has_many :followables    ,dependent: :destroy
  has_many :followers, through: :followables


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.order('followers_count DESC').limit(10)
  end

  def refresh
    require 'open-uri'


    page = Nokogiri::HTML(open('http://twitaholic.com/top100/followers/'))
    links =  page.css('html body div#container div#mainspace div#therest table tbody tr td.statcol_name a')
    screen_names = []
    links.each { |x| screen_names << x["href"].sub(/\//, "").chomp('/') }
    twitter_client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV['CONSUMER_KEY']
      config.consumer_secret     = ENV['CONSUMER_SECRET']
      config.access_token        = ENV['ACCESS_TOKEN']
      config.access_token_secret = ENV['ACCESS_TOKEN_SECRET']
    end
    User.destroy_all
    # get all users by screen names
    twitter_client.users(screen_names).each do |twitter_user|
      begin
        user = User.create(name: twitter_user.name,screen_name: twitter_user.screen_name,twitter_id: twitter_user.id,followers_count: twitter_user.followers_count )
        # retrieve followers of the user
        followers = twitter_client.followers(user.twitter_id,count: 5 )
        followers.each do |follower|
          follower_user = User.create(name: follower.name,screen_name: follower.screen_name,twitter_id: follower.id,followers_count: follower.followers_count )
          user.followables.create(follower_id: follower_user.id)
        end
      rescue  Twitter::Error
        logger.error "Rate limit exceeds"
        retry
      end
    end
  end

  def followers
    @user = User.where(screen_name: params[:screen_name]).first
    @followers = @user.followers.order('followers_count DESC')
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/followers.html.erb
<h3> Followers of <%= @user.name %>    </h3>
<%= link_to 'Back' ,users_path%>

<table>
  <th>Name</th>
  <th>Screen Name</th>
  <th>Twitter Id</th>
  <th>Followers Count</th>
  <th></th>
  <% unless @followers.blank? %>
      <% @followers.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.screen_name %></td>
            <td><%= user.twitter_id %></td>
            <td><%=  user.followers_count  %></td>
            <td><%= link_to 'Followers' ,followers_path(user.screen_name) %></td>
          </tr>
      <% end  %>
  <% end %>

</table>
<%= link_to 'Back' ,users_path%>

app/views/users/index.html.erb
<table>
  <th>Name</th>
  <th>Screen Name</th>
  <th>Twitter Id</th>
  <th>Followers Count</th>
  <th></th>
  <% unless @users.blank? %>
      <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.screen_name %></td>
            <td><%= user.twitter_id %></td>
            <td><%=  user.followers_count  %></td>
            <td><%= link_to 'Followers' ,followers_path(user.screen_name) %></td>
          </tr>
      <% end  %>
  <% end %>

</table>