config/routes.rb
InfluenceMarket::Application.routes.draw do

  match "users/top"=>'users#index',as: :users
  match 'users/:screen_name/followers' => 'users#followers' ,as: :followers
  match 'users/refresh' => 'users#refresh',as: :refresh_users

  resources :search do 
    collection do
      post :search_result
    end
  end

  resources :trades do
    member do 
      get :get_current_price
    end
  end

  resources :researchs
  resources :performances
  resources :sessions, :only => [:new, :create, :destroy]
  resources :home, :only => [:index]

   root :to => 'home#index'

end

app/views/layouts/_application_scripts.html.erb
<script type="text/javascript">
			$(function () {
			  // TinyNav.js 1
			  $('#nav').tinyNav({
			    active: 'selected',
			    //label: 'Menu'  
			  });

			});
	      </script>  
	      <script type="text/javascript"> 
			function show( id ) { 
				document.getElementById(id).style.display = 'block'; 
			} 
			function hide( id ) { 
				document.getElementById(id).style.display = 'none'; 
			} 
		</script>  
	        
		<!-- for quote hide show -->
		<script type="text/javascript"> 
			$(document).ready(function() {
				$('#quote_option').change(function(){
					var quote = $(this).val(),
					div = $('#' + quote);
					$('div.quote').hide();
					div.show();
				});
			});	
		</script>   
	        
		<!-- notification -->
		<script type="text/javascript">
			function showHide(obj) {
				var div = document.getElementById(obj);
				if (div.style.display == 'none') {
				div.style.display = '';
			} else {
				div.style.display = 'none';
				}
			}
		</script>
	        
		<!-- notification responsive -->
		<script type="text/javascript">
			function showHide_responsive(obj) {
			   var div = document.getElementById(obj);
			   if (div.style.display == 'none') {
				 div.style.display = '';
			   }
			   else {
				 div.style.display = 'none';
			   }
			 }
		</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<p>&copy; Copyright 2013 Auction market - Privacy Policy</p>
</footer>

app/views/layouts/_header.html.erb
<header>
   <!-- logo starts -->
    <a href="index.html" class="logo">Influence Market</a>
   <!-- logo ends --> 
   <!-- top link bar starts -->
   <% if session[:user].present? %>
    <div class="top_link">
        <ul>
        	<li style="position:relative;">
            	<!-- show hide portion for responsive version starts -->
                <div class="msg_cont responsive_notify">                    	
                  <div onclick="showHide_responsive('hidden_div_responsive'); return false;" class="icon">3</div>
                  <div id="hidden_div_responsive" style="display: none;">
                    <span class="arrow"></span>
                    <div class="show_hide_box">
                        <!-- repeating div starts -->
                        <div class="rpt_row">
                            <h3>Message:</h3>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                        </div>
                        <!-- repeating div ends -->
                        
                        <!-- repeating div starts -->
                        <div class="rpt_row">
                            <h3>Message:</h3>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                        </div>
                        <!-- repeating div ends -->
                     </div>
                  </div>
                </div>
         		<!-- show hide portion for responsive version ends -->
            </li>
            <li><%= link_to "Sign out",session_path(1), :class => "signout", :method => :delete %></li>
            <li><a href="#" class="acc_settings">Account settings</a></li>
            <li><%= link_to 'Top Users' ,users_path %></li>
            <li><%= link_to 'Refresh' ,refresh_users_path %></li>
        </ul>
        <div class="clearfix"></div>   
    </div>
    <% end %>
   <!-- top link bar ends -->   
</header>

app/views/layouts/_navigation_links.html.erb
<!-- navigation starts -->
<nav>
  <div  class="bg_nav_res" style="width: 102%;">
    <ul id="nav">
	<li class="search">
		<%= link_to "Search", root_url, :class => "#{(params[:controller] == "home" && params[:action] == "index") ? 'active' : '' }" %>
	</li>
	<li class="trade">
		<%= link_to "Trade", trades_path, :class => "#{(params[:controller] == "trades" && params[:action] == "index") ? 'active' : '' }" %>
	</li>
	<li class="performance">
		<%= link_to "Performances", performances_path, :class => "#{(params[:controller] == "performances" && params[:action] == "index") ? 'active' : '' }" %>
	</li>
	<li class="research">
		<%= link_to "Researchs", researchs_path, :class => "#{(params[:controller] == "researchs" && params[:action] == "index") ? 'active' : '' }" %>
	</li>
	<li class="notifications" style="position:relative;">
        	<a href="#">Notifications</a>
            <!-- show hide portion -->
            <div class="msg_cont">                    	
              <div onclick="showHide('hidden_div'); return false;" class="icon">3</div>
              <div id="hidden_div" style="display: none;">
                <span class="arrow"></span>
                <div class="show_hide_box">
                    <!-- repeating div starts -->
                    <div class="rpt_row">
                        <h3>Message:</h3>
                        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                    </div>
                    <!-- repeating div ends -->
                    
                    <!-- repeating div starts -->
                    <div class="rpt_row">
                        <h3>Message:</h3>
                        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                    </div>
                    <!-- repeating div ends -->
                 </div>
              </div>
            </div>
            <!-- show hide portion -->
        </li>
    </ul>
    <div class="clearfix"></div>
   </div> 
</nav>
<!-- navigation ends -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Influence Market</title>
		<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
		<meta name="description" content="">
		<meta name="author" content="">
		<!-- stylesheet -->
		<%#= stylesheet_link_tag   "style", "responsive" %>
		<%= stylesheet_link_tag   "application" %>

		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->	
		<%#= javascript_include_tag "jquery","html5","tinynav.min","tinynav" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<!-- for tiny nav -->
		<%= render :partial => "layouts/application_scripts" %>
		<%= yield :head_javascripts %>
	</head>
	<body>
		<div id="pagewrap">
			<!-- header starts -->
			<%= render :partial => "layouts/header" %>
			<!-- header ends -->
			<%= render :partial => "layouts/navigation_links" if session[:user].present? %>
			
		      <div style=""><%#= flash[:alert] %></div>
			<!-- body container starts -->
			<%= yield %>
			<!-- body container ends -->
		</div>      
			<!-- footer starts -->
	   		<%= render :partial => "layouts/footer" %>
			<!-- footer ends -->
			<!-- for modal view -->
		<%#= javascript_include_tag "jquery.simplemodal","basic" %>
	</body>
</html>